### ISSUE TITLE
Invitation by e-mail does not work

### ISSUE THREAD

**Issue by bruno-infotrad** [ColdTrick/group_tools#100]
For 1.10 (but I am pretty sure it applies to the latest version):
When trying to invite via the "Using email address" tab, I get the error "Invalid input to perform this action". I traced it to the fact that the _user_guid_email_ variable never gets populated.

**Comment by jeabakker** [comment]
have you selected the email address from the drop-down? Or was the drop-down not shown yet and did you hit ENTER? If so then the email address wasn't yet set so you get this error.

The ENTER issue was fixed in 326f9f3f943ad1f6ab6adfd8d54b9094161d2f82 and will not be backported to older versions. 

Please consider updating your Elgg installation as 1.10 is out of support http://learn.elgg.org/en/2.0/appendix/support.html
