### ISSUE TITLE
"Missing access level name" with walled garden 

### ISSUE THREAD

**Issue by iionly** [ColdTrick/group_tools#142]
If you have the walled garden option enabled or using the Loginrequired plugin the "public" access level gets unset.

On the Access tab of the group edit page you can select the access level for "Who can see this group". Problem is that the public access level is included in the selection but showing up as "Missing access level name" due to the public access level unset and therefor the corresponding label not being available.

Best would be to not offer the "public" access level at all in this selection when walled garden (or Loginrequired plugin) is enabled.

**Comment by jeabakker** [comment]
The plugin should already fix this for walled garden cases
https://github.com/ColdTrick/group_tools/blob/v9.4/views/default/groups/edit/access.php#L63-L89

And the string 'Missing access level' is a short coming of Elgg 2.3 and fixed in 3.

2.3 code: https://github.com/Elgg/Elgg/blob/2.3/views/default/input/access.php#L90-L94
3.0 code: https://github.com/Elgg/Elgg/blob/3.0/views/default/input/access.php#L81-L83

**Comment by iionly** [comment]
It is/was an issue of "or using the Loginrequired plugin" with overriding access.php again after group_tools already overrides access.php. Loginrequired overrides access.php to unset public access level as it provides a walled garden on its own without the core walled_garden config variable "on". But with also using group_tools the specific access.php of group_tools is not taken into account (the only sign that something was wrong was the "Missing access level" label). With overriding access.php with a customized version of access.php taken from group_tools it works correctly with both group_tools and loginrequired plugins in parallel.
