### ISSUE TITLE
No start.php file to allow activation

### ISSUE THREAD

**Issue by Kaidok5797** [ColdTrick/group_tools#157]
**Elgg version**
Which version of Elgg are you using: 3.3

**Plugin version**
Which version of the plugin are you using: Lates

**Plugin source**
- Elgg community page download

**Describe the bug**
I keep getting an error for all of your Elgg plugins that they cannot be activated because start.php is missing. I've looked in the directories and there is not a start.php file.

**Comment by jeabakker** [comment]
In Elgg 3.3 the need for a `start.php` was removed, if you're getting an error 'missing start.php' then you're not using Elgg 3.3, but some older version.

Please check your Elgg version, version prior to Elgg 3.1 go to admin/server, since Elgg 3.1 the version number can be found in the topbar on any page in the /admin section.

**Comment by jdalsem** [comment]
If you still think something is wrong (after you have checked the previous comment) let us know
